"""init model

Revision ID: 9f8dc4434c46
Revises: d3f48be0585c
Create Date: 2024-10-15 15:01:22.023555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f8dc4434c46"
down_revision: Union[str, None] = "d3f48be0585c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "City",
        sa.Column("id_city", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("name_city", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id_city"),
    )
    op.drop_table("User")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id_city", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "lat", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column(
            "lon", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column("name_city", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id_city", name="User_pkey"),
    )
    op.drop_table("City")
    # ### end Alembic commands ###
